// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: internal/proto/summary.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SummaryNewsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SummaryNewsRequest) Reset() {
	*x = SummaryNewsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_summary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummaryNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryNewsRequest) ProtoMessage() {}

func (x *SummaryNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_summary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryNewsRequest.ProtoReflect.Descriptor instead.
func (*SummaryNewsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_summary_proto_rawDescGZIP(), []int{0}
}

func (x *SummaryNewsRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SummaryNewsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success        bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SummarizedText string `protobuf:"bytes,2,opt,name=summarized_text,json=summarizedText,proto3" json:"summarized_text,omitempty"`
}

func (x *SummaryNewsResponse) Reset() {
	*x = SummaryNewsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_summary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummaryNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryNewsResponse) ProtoMessage() {}

func (x *SummaryNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_summary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryNewsResponse.ProtoReflect.Descriptor instead.
func (*SummaryNewsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_summary_proto_rawDescGZIP(), []int{1}
}

func (x *SummaryNewsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SummaryNewsResponse) GetSummarizedText() string {
	if x != nil {
		return x.SummarizedText
	}
	return ""
}

var File_internal_proto_summary_proto protoreflect.FileDescriptor

var file_internal_proto_summary_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x26,
	0x0a, 0x12, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x4e, 0x65, 0x77, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x58, 0x0a, 0x13, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x4e, 0x65, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x54, 0x65, 0x78, 0x74,
	0x32, 0x6c, 0x0a, 0x0e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x5a, 0x0a, 0x0d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x4e,
	0x65, 0x77, 0x73, 0x12, 0x22, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x4e, 0x65, 0x77, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x4e, 0x65, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x30,
	0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x6f, 0x75,
	0x72, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_summary_proto_rawDescOnce sync.Once
	file_internal_proto_summary_proto_rawDescData = file_internal_proto_summary_proto_rawDesc
)

func file_internal_proto_summary_proto_rawDescGZIP() []byte {
	file_internal_proto_summary_proto_rawDescOnce.Do(func() {
		file_internal_proto_summary_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_summary_proto_rawDescData)
	})
	return file_internal_proto_summary_proto_rawDescData
}

var file_internal_proto_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_summary_proto_goTypes = []any{
	(*SummaryNewsRequest)(nil),  // 0: summaryservice.SummaryNewsRequest
	(*SummaryNewsResponse)(nil), // 1: summaryservice.SummaryNewsResponse
}
var file_internal_proto_summary_proto_depIdxs = []int32{
	0, // 0: summaryservice.SummaryService.SummarizeNews:input_type -> summaryservice.SummaryNewsRequest
	1, // 1: summaryservice.SummaryService.SummarizeNews:output_type -> summaryservice.SummaryNewsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_summary_proto_init() }
func file_internal_proto_summary_proto_init() {
	if File_internal_proto_summary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_summary_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SummaryNewsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_summary_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SummaryNewsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_summary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_summary_proto_goTypes,
		DependencyIndexes: file_internal_proto_summary_proto_depIdxs,
		MessageInfos:      file_internal_proto_summary_proto_msgTypes,
	}.Build()
	File_internal_proto_summary_proto = out.File
	file_internal_proto_summary_proto_rawDesc = nil
	file_internal_proto_summary_proto_goTypes = nil
	file_internal_proto_summary_proto_depIdxs = nil
}
