version: "3.8"
services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gateway?schema=public

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gateway
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
