services:
  gateway:
    build: .
    container_name: gateway
    hostname: gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gateway?schema=public
      - SCRAPER_SERVICE=news_service:50051
      - VOICE_SERVICE=voice_service:50052
      - SUMMARY_SERVICE=summary_service:50053
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRATION_HOURS=24
      - PORT=8080
      - FRONTEND_URL=http://nginx:80
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gateway
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    external: true
